import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";

import LocalFont from "next/font/local";
import localFont from "next/font/local";
import { CSSProperties } from "react";
import Header from "./(components)/header/Header";
import Footer from "./(components)/footer/Footer";
import Loading from "./(components)/loading/Loading";
// import "react-slick/";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const CircularStd = localFont({
  src: [
    {
      path: "fonts/CircularStd-Black.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "fonts/CircularStd-Black.ttf",
      weight: "800",
      style: "bolder",
    },
    {
      path: "fonts/CircularStd-Medium.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/CircularStd-Book.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--fontMain",
});

export const metadata: Metadata = {
  title: "EROI!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body
        className={`topofpage`}
        style={{ "--fontM": CircularStd.style.fontFamily } as CSSProperties}
      >
        <Loading />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
